######################################################################
# Automatically generated by qmake (3.0) Tue Jan 5 15:52:13 2016
######################################################################

TEMPLATE = app
TARGET = ttsg
INCLUDEPATH += .

QT += xml

# Input
SOURCES += main.cpp
